

package chat;

import java.awt.Font;
import java.net.Socket;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/**
 *
 
 */
public class VCliente extends javax.swing.JFrame {
//***** Declaración de variables**************************************     
	//VARIABLE
    private MCliente cliente=null;
    //JPanel
    private JPanel contentPane;
    //JLabel
    private JLabel lbl_titulo_cliente;
    private JLabel lbl_puerto;
    private JLabel lbl_url ;
    //JTextField
    private JTextField jt_puerto;
    private JTextField jt_ip;
    private JTextField jTextField3;
    private JTextField jt_nick;
    //JButton
    private JButton jb_conectar;
    private JButton jb_desconectar;
    //JScrollPane
    private JScrollPane scrollPane_chat ;
    private JScrollPane scrollPane_contactos;
    //DefaultListModel
    private DefaultListModel modeloLista ;
    //JList
    private JList list_contactos;
   //JTextArea
    private JTextArea tArea_chat;
  //------ Fin de declaración de variables ----------------------------   
   
    /** Creates new form VCliente */
    public VCliente() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {
        

    	this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        setBounds(100, 100, 640, 500);
        contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null); //absolute layout
        
		lbl_titulo_cliente = new JLabel();
        lbl_titulo_cliente.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbl_titulo_cliente.setText("Cliente");
        lbl_titulo_cliente.setBounds(194, 11, 201, 14);
		contentPane.add(lbl_titulo_cliente);

		lbl_puerto = new JLabel();
		lbl_puerto.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbl_puerto.setText("Puerto");
        lbl_puerto.setBounds(104, 60, 201, 14);
		contentPane.add(lbl_puerto);
		
		lbl_url = new JLabel();
		lbl_url.setFont(new java.awt.Font("Tahoma", 1, 18));
		lbl_url.setText("URL");
		lbl_url.setBounds(104, 110, 201, 14);
		contentPane.add(lbl_url);

		jt_puerto = new JTextField();
		jt_puerto.setFont(new Font("Tahoma", Font.BOLD, 11));
        jt_puerto.setText("7878");
        jt_puerto.setBounds(302, 60, 201, 20);
		contentPane.add(jt_puerto);
		jt_puerto.setColumns(10);
        

		jt_ip = new javax.swing.JTextField();
		jt_ip.setFont(new Font("Tahoma", Font.BOLD, 11));
        jt_ip.setText("127.0.0.1");
        jt_ip.setBounds(302, 110, 201, 20);
        contentPane.add(jt_ip);
        jt_ip.setColumns(10);
		
		

		jb_conectar = new JButton();
        jb_conectar.setText("Conectar");
        jb_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jb_conectar.setBounds(209, 344, 89, 23);
		contentPane.add(jb_conectar);
        

        jTextField3 = new JTextField();
        jTextField3.setFont(new Font("Tahoma", Font.BOLD, 11));
        jTextField3.setBounds(250, 156, 253, 20);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        contentPane.add(jTextField3);
        jTextField3.setColumns(10);
        

        jt_nick = new JTextField();
        jt_nick.setFont(new Font("Tahoma", Font.BOLD, 11));
        jt_nick.setText("Nick");
        jt_nick.setBounds(104, 156, 61, 20);
        contentPane.add(jt_nick);
        jt_nick.setColumns(10);

       
        

        jb_desconectar = new JButton();
        jb_desconectar.setText("Desconectar");
        jb_desconectar.setEnabled(false);
        jb_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jb_desconectar.setBounds(413, 344, 108, 23);
		contentPane.add(jb_desconectar);
		
		scrollPane_chat = new JScrollPane();
		scrollPane_chat.setBounds(28, 185, 475, 148);
		contentPane.add(scrollPane_chat);
		
		tArea_chat = new JTextArea();
		scrollPane_chat.setViewportView(tArea_chat);
		
		scrollPane_contactos = new JScrollPane();
		scrollPane_contactos.setBounds(525, 185, 89, 148);
		contentPane.add(scrollPane_contactos);
		
		list_contactos = new JList();
		scrollPane_contactos.setViewportView(list_contactos);
		
		

    } //fin private void initComponents()

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        if (cliente!=null){
            cliente.enviarTrama(3, "");
            cliente.interrupt();
        }
        cliente = null;
        jb_conectar.setEnabled(true);
        jb_desconectar.setEnabled(false);
        dlm.removeAllElements();
        tArea_chat.setText("");
    }//fin private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
// TODO add your handling code here:
        if (evt.getKeyCode()==10){
            cliente.enviarMensaje(jTextField3.getText());
            jTextField3.setText("");
        }
    }//fin private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

    DefaultListModel dlm=new DefaultListModel();
    
   // private JList list_contactos;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    	list_contactos.setModel(dlm);
        try{
        	//String valor = jt_nick.getText();
			//modeloLista.addElement(valor);
            int port = Integer.parseInt(jt_puerto.getText());
            String url = jt_ip.getText();
            String nick = jt_nick.getText();
            if (cliente==null){
                cliente = new MCliente(port,url,nick,this);
                cliente.start();
            }
            jb_conectar.setEnabled(false);
            jb_desconectar.setEnabled(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error en la entrada de datos");
            cliente=null;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void mensajeRecibido(String sMensaje){
    	tArea_chat.append(sMensaje + "\n");
    }
    
    public void nuevaPersona(String nick){
        dlm.addElement(nick);
    }
    
    public void borrarPersona(int nPos){
        dlm.remove(nPos);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }
}
