

package chat;

import java.awt.Font;
import java.net.ServerSocket;
import java.net.Socket;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/**
 *
 * 
 */
public class VServidor extends javax.swing.JFrame {
	//***** Declaración de variables**************************************  
	//VARIABLE
    private MServidor servidor = null;
    //JPanel
    private JPanel contentPane;
  //JLabel
    private JLabel jl_servidor;
    private JLabel jl_puerto;
  //JTextField
    private JTextField jt_puerto;
  //JButton
    private JButton btn_abrirPuerto;
  //------ Fin de declaración de variables ---------------------------- 
    
    
    /** Creates new form VServidor */
    public VServidor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {
       

    	this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(100, 100, 200, 200);
        contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null); //absolute layout
        
		jl_servidor = new JLabel();
        jl_servidor.setFont(new java.awt.Font("Tahoma", 1, 18));
        jl_servidor.setText("Servidor");
        jl_servidor.setBounds(41, 11, 86, 14);
        contentPane.add(jl_servidor);

        jl_puerto = new JLabel();
        jl_puerto.setFont(new java.awt.Font("Tahoma", 1, 18));
        jl_puerto.setText("Puerto");
        jl_puerto.setBounds(10, 51, 86, 14);
        contentPane.add(jl_puerto);

        jt_puerto = new JTextField();
        jt_puerto.setFont(new Font("Tahoma", Font.BOLD, 11));
        jt_puerto.setText("7878");
        jt_puerto.setBounds(106, 51, 86, 20);
		contentPane.add(jt_puerto);
		jt_puerto.setColumns(10);

		btn_abrirPuerto = new JButton();
        btn_abrirPuerto.setText("Abrir puerto");
        btn_abrirPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                btn_abrirPuerto.setEnabled(false);
                btn_abrirPuerto.setText("Puerto abierto");
                JOptionPane.showMessageDialog(null,"El servidor se ha iniciado.");
            }
        });
        btn_abrirPuerto.setBounds(29, 100, 129, 23);
		contentPane.add(btn_abrirPuerto);

    }//fin private void initComponents()

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (servidor==null){
            int port = Integer.parseInt(jt_puerto.getText());
            servidor = new MServidor(this, port);
            servidor.start();
        }
    }//fin private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VServidor().setVisible(true);
            }
        });
    }
    
  
}
